/**
 * Canonical domain event type registry for the finance module.
 * All producers and consumers MUST reference these constants.
 * A typo becomes a compile-time error, not a silent runtime mismatch.
 */
export const FinanceEventType = {
  JOURNAL_CREATED: 'JOURNAL_CREATED',
  JOURNAL_POSTED: 'JOURNAL_POSTED',
  JOURNAL_REVERSED: 'JOURNAL_REVERSED',
  JOURNAL_VOIDED: 'JOURNAL_VOIDED',
  GL_BALANCE_CHANGED: 'GL_BALANCE_CHANGED',
  PERIOD_CLOSED: 'PERIOD_CLOSED',
  PERIOD_LOCKED: 'PERIOD_LOCKED',
  PERIOD_REOPENED: 'PERIOD_REOPENED',
  YEAR_CLOSED: 'YEAR_CLOSED',
  IC_TRANSACTION_CREATED: 'IC_TRANSACTION_CREATED',
  IC_SETTLEMENT_CONFIRMED: 'IC_SETTLEMENT_CONFIRMED',
  REVENUE_RECOGNIZED: 'REVENUE_RECOGNIZED',
  RECURRING_JOURNAL_CREATED: 'RECURRING_JOURNAL_CREATED',
  RECURRING_JOURNALS_PROCESSED: 'RECURRING_JOURNALS_PROCESSED',
  AP_INVOICE_APPROVED: 'AP_INVOICE_APPROVED',
  AP_INVOICE_CANCELLED: 'AP_INVOICE_CANCELLED',
  AP_INVOICE_POSTED: 'AP_INVOICE_POSTED',
  AP_INVOICE_PAID: 'AP_INVOICE_PAID',
  AP_PAYMENT_RUN_EXECUTED: 'AP_PAYMENT_RUN_EXECUTED',
  AP_PAYMENT_RUN_REVERSED: 'AP_PAYMENT_RUN_REVERSED',
  AP_DEBIT_MEMO_CREATED: 'AP_DEBIT_MEMO_CREATED',
  AR_INVOICE_POSTED: 'AR_INVOICE_POSTED',
  AR_INVOICE_PAID: 'AR_INVOICE_PAID',
  AR_PAYMENT_ALLOCATED: 'AR_PAYMENT_ALLOCATED',
  AR_WRITE_OFF_APPROVED: 'AR_WRITE_OFF_APPROVED',
  AR_CREDIT_NOTE_CREATED: 'AR_CREDIT_NOTE_CREATED',
  AR_DUNNING_RUN_CREATED: 'AR_DUNNING_RUN_CREATED',
  TAX_RETURN_CALCULATED: 'TAX_RETURN_CALCULATED',
  TAX_RETURN_FILED: 'TAX_RETURN_FILED',
  WHT_CERTIFICATE_ISSUED: 'WHT_CERTIFICATE_ISSUED',
  TAX_PROVISION_COMPUTED: 'TAX_PROVISION_COMPUTED',
  ASSET_ACQUIRED: 'ASSET_ACQUIRED',
  ASSET_DEPRECIATED: 'ASSET_DEPRECIATED',
  ASSET_REVALUED: 'ASSET_REVALUED',
  ASSET_IMPAIRED: 'ASSET_IMPAIRED',
  ASSET_DISPOSED: 'ASSET_DISPOSED',
  ASSET_TRANSFERRED: 'ASSET_TRANSFERRED',
  BANK_STATEMENT_IMPORTED: 'BANK_STATEMENT_IMPORTED',
  BANK_AUTO_MATCH_COMPLETED: 'BANK_AUTO_MATCH_COMPLETED',
  BANK_MATCH_CONFIRMED: 'BANK_MATCH_CONFIRMED',
  BANK_RECONCILIATION_SIGNED_OFF: 'BANK_RECONCILIATION_SIGNED_OFF',
  CREDIT_LIMIT_SET: 'CREDIT_LIMIT_SET',
  CREDIT_HOLD_PLACED: 'CREDIT_HOLD_PLACED',
  CREDIT_HOLD_RELEASED: 'CREDIT_HOLD_RELEASED',
  CREDIT_REVIEW_COMPLETED: 'CREDIT_REVIEW_COMPLETED',
  BAD_DEBT_WRITTEN_OFF: 'BAD_DEBT_WRITTEN_OFF',
  EXPENSE_CLAIM_SUBMITTED: 'EXPENSE_CLAIM_SUBMITTED',
  EXPENSE_CLAIM_APPROVED: 'EXPENSE_CLAIM_APPROVED',
  EXPENSE_CLAIM_REJECTED: 'EXPENSE_CLAIM_REJECTED',
  EXPENSE_CLAIM_REIMBURSED: 'EXPENSE_CLAIM_REIMBURSED',
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_COST_POSTED: 'PROJECT_COST_POSTED',
  PROJECT_BILLED: 'PROJECT_BILLED',
  PROJECT_WIP_TRANSFERRED: 'PROJECT_WIP_TRANSFERRED',
  PROJECT_COMPLETED: 'PROJECT_COMPLETED',
  LEASE_CREATED: 'LEASE_CREATED',
  LEASE_ACTIVATED: 'LEASE_ACTIVATED',
  LEASE_MODIFIED: 'LEASE_MODIFIED',
  LEASE_TERMINATED: 'LEASE_TERMINATED',
  PROVISION_CREATED: 'PROVISION_CREATED',
  PROVISION_UTILISED: 'PROVISION_UTILISED',
  PROVISION_REVERSED: 'PROVISION_REVERSED',
  PROVISION_REMEASURED: 'PROVISION_REMEASURED',
  CASH_FORECAST_CREATED: 'CASH_FORECAST_CREATED',
  COVENANT_TESTED: 'COVENANT_TESTED',
  COVENANT_BREACHED: 'COVENANT_BREACHED',
  IC_LOAN_CREATED: 'IC_LOAN_CREATED',
  IC_LOAN_REPAID: 'IC_LOAN_REPAID',
  COST_CENTER_CREATED: 'COST_CENTER_CREATED',
  COST_DRIVER_CREATED: 'COST_DRIVER_CREATED',
  COST_ALLOCATION_COMPLETED: 'COST_ALLOCATION_COMPLETED',
  COST_ALLOCATION_REVERSED: 'COST_ALLOCATION_REVERSED',
  GROUP_ENTITY_CREATED: 'GROUP_ENTITY_CREATED',
  OWNERSHIP_CHANGED: 'OWNERSHIP_CHANGED',
  GOODWILL_RECOGNIZED: 'GOODWILL_RECOGNIZED',
  GOODWILL_IMPAIRED: 'GOODWILL_IMPAIRED',
  CONSOLIDATION_COMPLETED: 'CONSOLIDATION_COMPLETED',
  RECONCILIATION_COMPLETED: 'RECONCILIATION_COMPLETED',
  RECONCILIATION_EXCEPTION: 'RECONCILIATION_EXCEPTION',
  EXCEPTION_REPORT_GENERATED: 'EXCEPTION_REPORT_GENERATED',
  ACCESS_REVIEW_COMPLETED: 'ACCESS_REVIEW_COMPLETED',
  CONCURRENCY_CONFLICT_DETECTED: 'CONCURRENCY_CONFLICT_DETECTED',
  APPROVAL_SUBMITTED: 'APPROVAL_SUBMITTED',
  APPROVAL_APPROVED: 'APPROVAL_APPROVED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  AP_CREDIT_MEMO_CREATED: 'AP_CREDIT_MEMO_CREATED',
  AP_PREPAYMENT_CREATED: 'AP_PREPAYMENT_CREATED',
  AP_PREPAYMENT_APPLIED: 'AP_PREPAYMENT_APPLIED',
  AP_INVOICE_BATCH_IMPORTED: 'AP_INVOICE_BATCH_IMPORTED',
  AP_BANK_REJECTION_PROCESSED: 'AP_BANK_REJECTION_PROCESSED',
  AP_REMITTANCE_ADVICE_GENERATED: 'AP_REMITTANCE_ADVICE_GENERATED',
  AP_WHT_CERTIFICATE_ISSUED: 'AP_WHT_CERTIFICATE_ISSUED',
  SUPPLIER_BANK_ACCOUNT_UPDATED: 'SUPPLIER_BANK_ACCOUNT_UPDATED',
  SUPPLIER_PROFILE_UPDATED: 'SUPPLIER_PROFILE_UPDATED',
  SUPPLIER_INVOICE_SUBMITTED: 'SUPPLIER_INVOICE_SUBMITTED',
  SUPPLIER_REMITTANCE_DOWNLOADED: 'SUPPLIER_REMITTANCE_DOWNLOADED',
  SUPPLIER_STATEMENT_UPLOADED: 'SUPPLIER_STATEMENT_UPLOADED',
  SUPPLIER_DOCUMENT_UPLOADED: 'SUPPLIER_DOCUMENT_UPLOADED',
  SUPPLIER_DISPUTE_CREATED: 'SUPPLIER_DISPUTE_CREATED',
  SUPPLIER_DISPUTE_RESOLVED: 'SUPPLIER_DISPUTE_RESOLVED',
  AP_INVOICE_MARKED_INCOMPLETE: 'AP_INVOICE_MARKED_INCOMPLETE',
  AP_TRIAGE_ASSIGNED: 'AP_TRIAGE_ASSIGNED',
  AP_TRIAGE_RESOLVED: 'AP_TRIAGE_RESOLVED',
  AP_OCR_REQUESTED: 'AP_OCR_REQUESTED',
  AP_OCR_EXTRACTION_FAILED: 'AP_OCR_EXTRACTION_FAILED',
  AP_OCR_INVOICE_RECEIVED: 'AP_OCR_INVOICE_RECEIVED',
  SUPPLIER_BLOCKED: 'SUPPLIER_BLOCKED',
  SUPPLIER_UNBLOCKED: 'SUPPLIER_UNBLOCKED',
  SUPPLIER_BLACKLISTED: 'SUPPLIER_BLACKLISTED',
  SUPPLIER_BLACKLIST_REVERSED: 'SUPPLIER_BLACKLIST_REVERSED',
  SUPPLIER_ACTIVATED: 'SUPPLIER_ACTIVATED',
  SUPPLIER_ACTIVATION_REQUESTED: 'SUPPLIER_ACTIVATION_REQUESTED',
  SUPPLIER_LEGAL_DOC_ADDED: 'SUPPLIER_LEGAL_DOC_ADDED',
  SUPPLIER_LEGAL_DOC_VERIFIED: 'SUPPLIER_LEGAL_DOC_VERIFIED',
  SUPPLIER_LEGAL_DOC_REJECTED: 'SUPPLIER_LEGAL_DOC_REJECTED',
  SUPPLIER_LEGAL_DOC_EXPIRED: 'SUPPLIER_LEGAL_DOC_EXPIRED',
  SUPPLIER_EVALUATION_CREATED: 'SUPPLIER_EVALUATION_CREATED',
  SUPPLIER_EVALUATION_SUBMITTED: 'SUPPLIER_EVALUATION_SUBMITTED',
  SUPPLIER_EVALUATION_APPROVED: 'SUPPLIER_EVALUATION_APPROVED',
  SUPPLIER_RISK_RAISED: 'SUPPLIER_RISK_RAISED',
  SUPPLIER_RISK_RESOLVED: 'SUPPLIER_RISK_RESOLVED',
  SUPPLIER_DUPLICATE_DETECTED: 'SUPPLIER_DUPLICATE_DETECTED',
  SUPPLIER_DUPLICATE_MERGED: 'SUPPLIER_DUPLICATE_MERGED',
  // @afenda-gen:events:start
  // ─── Portal Case Management (Phase 1.1) ───
  SUPPLIER_CASE_CREATED: 'SUPPLIER_CASE_CREATED',
  SUPPLIER_CASE_STATUS_CHANGED: 'SUPPLIER_CASE_STATUS_CHANGED',
  SUPPLIER_CASE_ASSIGNED: 'SUPPLIER_CASE_ASSIGNED',
  SUPPLIER_CASE_RESOLVED: 'SUPPLIER_CASE_RESOLVED',
  SUPPLIER_CASE_TIMELINE_ENTRY: 'SUPPLIER_CASE_TIMELINE_ENTRY',
  SUPPLIER_CASE_SLA_BREACHED: 'SUPPLIER_CASE_SLA_BREACHED',
  // ─── Portal Compliance Expiry Alerts (Phase 1.1.3 CAP-COMPL) ───
  SUPPLIER_COMPLIANCE_EXPIRING: 'SUPPLIER_COMPLIANCE_EXPIRING',
  SUPPLIER_COMPLIANCE_EXPIRED: 'SUPPLIER_COMPLIANCE_EXPIRED',
  SUPPLIER_COMPLIANCE_RENEWED: 'SUPPLIER_COMPLIANCE_RENEWED',
  SUPPLIER_COMPLIANCE_CASE_CREATED: 'SUPPLIER_COMPLIANCE_CASE_CREATED',
  // ─── Portal Onboarding Wizard (Phase 1.1.2 CAP-ONB) ───
  SUPPLIER_ONBOARDING_STARTED: 'SUPPLIER_ONBOARDING_STARTED',
  SUPPLIER_ONBOARDING_STEP_SAVED: 'SUPPLIER_ONBOARDING_STEP_SAVED',
  SUPPLIER_ONBOARDING_SUBMITTED: 'SUPPLIER_ONBOARDING_SUBMITTED',
  SUPPLIER_ONBOARDING_APPROVED: 'SUPPLIER_ONBOARDING_APPROVED',
  SUPPLIER_ONBOARDING_REJECTED: 'SUPPLIER_ONBOARDING_REJECTED',
  // ─── Portal Invitation Flow (Phase 1.1.7 CAP-INV) ───
  SUPPLIER_INVITED: 'SUPPLIER_INVITED',
  SUPPLIER_CREATED: 'SUPPLIER_CREATED',
  SUPPLIER_INVITATION_ACCEPTED: 'SUPPLIER_INVITATION_ACCEPTED',
  SUPPLIER_INVITATION_REVOKED: 'SUPPLIER_INVITATION_REVOKED',
  SUPPLIER_INVITATION_EXPIRED: 'SUPPLIER_INVITATION_EXPIRED',
  // ─── Portal Messaging Hub (Phase 1.2.1 CAP-MSG) ───
  SUPPLIER_MESSAGE_THREAD_STARTED: 'SUPPLIER_MESSAGE_THREAD_STARTED',
  SUPPLIER_MESSAGE_SENT: 'SUPPLIER_MESSAGE_SENT',
  SUPPLIER_MESSAGE_READ: 'SUPPLIER_MESSAGE_READ',
  // ─── Portal Breakglass Escalation (Phase 1.2.2 CAP-SOS P19) ───
  SUPPLIER_ESCALATION_TRIGGERED: 'SUPPLIER_ESCALATION_TRIGGERED',
  SUPPLIER_ESCALATION_ASSIGNED: 'SUPPLIER_ESCALATION_ASSIGNED',
  SUPPLIER_ESCALATION_RESOLVED: 'SUPPLIER_ESCALATION_RESOLVED',
  // @afenda-gen:events:end
} as const;

export type FinanceEventType = (typeof FinanceEventType)[keyof typeof FinanceEventType];

// ─── Event Tier & Family metadata ───────────────────────────────────────────

export type EventTier = 0 | 1;
export type EventFamily = 'audit' | 'notification' | 'document' | 'cache' | 'webhook';

export interface EventMeta {
  readonly tier: EventTier;
  readonly family: EventFamily;
}

const T1_NOTIFICATION: EventMeta = { tier: 1, family: 'notification' };
const T1_CACHE: EventMeta = { tier: 1, family: 'cache' };
const T1_DOCUMENT: EventMeta = { tier: 1, family: 'document' };
const T0_AUDIT: EventMeta = { tier: 0, family: 'audit' };

/**
 * Event tier registry. Tier-1 events MUST have real side-effects (email, cache
 * invalidation, document ops, webhooks). Tier-0 events are audit-only.
 *
 * Future modules add their own entries without modifying this file.
 */
export const EVENT_REGISTRY: Record<string, EventMeta> = {
  // Tier-1: notification (email/in-app)
  [FinanceEventType.JOURNAL_POSTED]: T1_NOTIFICATION,
  [FinanceEventType.APPROVAL_SUBMITTED]: T1_NOTIFICATION,
  [FinanceEventType.APPROVAL_APPROVED]: T1_NOTIFICATION,
  [FinanceEventType.APPROVAL_REJECTED]: T1_NOTIFICATION,
  [FinanceEventType.AP_PAYMENT_RUN_EXECUTED]: T1_NOTIFICATION,
  [FinanceEventType.EXPENSE_CLAIM_APPROVED]: T1_NOTIFICATION,
  [FinanceEventType.EXPENSE_CLAIM_REJECTED]: T1_NOTIFICATION,
  [FinanceEventType.COVENANT_BREACHED]: T1_NOTIFICATION,

  // Tier-1: cache invalidation
  [FinanceEventType.GL_BALANCE_CHANGED]: T1_CACHE,

  // Tier-1: document operations
  [FinanceEventType.AR_DUNNING_RUN_CREATED]: T1_DOCUMENT,

  // Tier-0: OCR pipeline audit
  [FinanceEventType.AP_OCR_REQUESTED]: T0_AUDIT,
  [FinanceEventType.AP_OCR_EXTRACTION_FAILED]: T0_AUDIT,

  // Tier-1: OCR invoice notification (triggers triage review)
  [FinanceEventType.AP_OCR_INVOICE_RECEIVED]: T1_NOTIFICATION,

  // Tier-1: Portal Case Management events
  [FinanceEventType.SUPPLIER_CASE_CREATED]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_CASE_STATUS_CHANGED]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_CASE_ASSIGNED]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_CASE_RESOLVED]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_CASE_SLA_BREACHED]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_CASE_TIMELINE_ENTRY]: T0_AUDIT,

  // Tier-1: Portal Compliance Expiry Alerts
  [FinanceEventType.SUPPLIER_COMPLIANCE_EXPIRING]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_COMPLIANCE_EXPIRED]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_COMPLIANCE_RENEWED]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_COMPLIANCE_CASE_CREATED]: T1_NOTIFICATION,

  // Tier-1: Portal Onboarding events
  [FinanceEventType.SUPPLIER_ONBOARDING_STARTED]: T0_AUDIT,
  [FinanceEventType.SUPPLIER_ONBOARDING_STEP_SAVED]: T0_AUDIT,
  [FinanceEventType.SUPPLIER_ONBOARDING_SUBMITTED]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_ONBOARDING_APPROVED]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_ONBOARDING_REJECTED]: T1_NOTIFICATION,

  // Tier-1: Portal Invitation events
  [FinanceEventType.SUPPLIER_INVITED]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_CREATED]: T0_AUDIT,
  [FinanceEventType.SUPPLIER_INVITATION_ACCEPTED]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_INVITATION_REVOKED]: T1_NOTIFICATION,
  [FinanceEventType.SUPPLIER_INVITATION_EXPIRED]: T1_NOTIFICATION,
};

/**
 * Returns the tier metadata for an event, defaulting to Tier-0 audit.
 */
export function getEventMeta(eventType: string): EventMeta {
  return EVENT_REGISTRY[eventType] ?? T0_AUDIT;
}
