#!/usr/bin/env node
/**
 * agents-gen.mjs — Auto-generate INDEX.md + INSTALLED-SKILLS.md from skills-registry.json + filesystem.
 *
 * Usage:
 *   node .agents/tools/agents-gen.mjs            # generate docs
 *   node .agents/tools/agents-gen.mjs --check     # dry-run: report drift without writing
 *
 * Zero dependencies — uses only Node.js built-ins.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const AGENTS_ROOT = resolve(__dirname, "..");
const SKILLS_DIR = join(AGENTS_ROOT, "skills");
const REGISTRY_PATH = join(AGENTS_ROOT, "skills-registry.json");
const INDEX_PATH = join(AGENTS_ROOT, "INDEX.md");
const INSTALLED_PATH = join(AGENTS_ROOT, "skills", "INSTALLED-SKILLS.md");

const CHECK_MODE = process.argv.includes("--check");

// ─── Helpers ────────────────────────────────────────────────────────────────

function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const fm = {};
  for (const line of match[1].split(/\r?\n/)) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if ((val.startsWith("'") && val.endsWith("'")) || (val.startsWith('"') && val.endsWith('"'))) {
      val = val.slice(1, -1);
    }
    fm[key] = val;
  }
  return fm;
}

function discoverSkillsOnDisk() {
  const dirs = readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  return dirs.map((name) => {
    const skillMd = join(SKILLS_DIR, name, "SKILL.md");
    const hasSkillMd = existsSync(skillMd);
    let frontmatter = {};
    if (hasSkillMd) {
      try {
        frontmatter = parseFrontmatter(readFileSync(skillMd, "utf-8"));
      } catch {
        /* ignore parse errors */
      }
    }
    return { name, hasSkillMd, frontmatter };
  });
}

function loadRegistry() {
  if (!existsSync(REGISTRY_PATH)) {
    console.error(`ERROR: Registry not found at ${REGISTRY_PATH}`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(REGISTRY_PATH, "utf-8"));
}

// ─── Validation ─────────────────────────────────────────────────────────────

function validate(registry, diskSkills) {
  const errors = [];
  const registryNames = new Set(registry.skills.map((s) => s.name));
  const diskNames = new Set(diskSkills.map((s) => s.name));

  for (const name of registryNames) {
    if (!diskNames.has(name)) {
      errors.push(`REGISTRY_ORPHAN: "${name}" is in registry but has no directory on disk`);
    }
  }
  for (const s of diskSkills) {
    if (!registryNames.has(s.name)) {
      errors.push(`DISK_ORPHAN: "${s.name}" exists on disk but is not in registry`);
    }
    if (!s.hasSkillMd) {
      errors.push(`MISSING_SKILL_MD: "${s.name}" directory exists but has no SKILL.md`);
    }
  }

  for (const skill of registry.skills) {
    if (!skill.name) errors.push(`INVALID_ENTRY: skill missing "name"`);
    if (!skill.category) errors.push(`INVALID_ENTRY: "${skill.name}" missing "category"`);
    if (!skill.description) errors.push(`INVALID_ENTRY: "${skill.name}" missing "description"`);
    if (!registry.categories[skill.category]) {
      errors.push(`UNKNOWN_CATEGORY: "${skill.name}" has category "${skill.category}" not in categories map`);
    }
  }

  return errors;
}

// ─── Generators ─────────────────────────────────────────────────────────────

function generateIndex(registry) {
  const now = new Date().toISOString().slice(0, 10);
  const total = registry.skills.length;
  const byCategory = {};
  for (const skill of registry.skills) {
    const cat = skill.category;
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push(skill);
  }

  let md = `<!-- AUTO-GENERATED by .agents/tools/agents-gen.mjs — do not edit manually -->\n`;
  md += `# AFENDA-NEXUS Agent Resources Index\n\n`;
  md += `Quick reference guide to agent resources in this workspace.\n\n`;
  md += `**Generated:** ${now}  \n`;
  md += `**Total Skills:** ${total}\n\n`;
  md += `---\n\n`;
  md += `## Quick Navigation\n\n`;
  md += `| Category | Skills |\n`;
  md += `| -------- | ------ |\n`;

  for (const [catKey, catLabel] of Object.entries(registry.categories)) {
    const skills = byCategory[catKey];
    if (!skills || skills.length === 0) continue;
    const links = skills.map((s) => `[${s.name}](#${s.name})`).join(", ");
    md += `| **${catLabel}** | ${links} |\n`;
  }

  md += `\n---\n\n`;
  md += `## Skills by Category\n\n`;

  for (const [catKey, catLabel] of Object.entries(registry.categories)) {
    const skills = byCategory[catKey];
    if (!skills || skills.length === 0) continue;
    md += `### ${catLabel}\n\n`;
    for (const s of skills) {
      md += `- **${s.name}** – ${s.description}\n`;
    }
    md += `\n`;
  }

  md += `---\n\n`;
  md += `## Full Skill Reference\n\n`;
  md += `See [skills/INSTALLED-SKILLS.md](./skills/INSTALLED-SKILLS.md) for detailed descriptions and usage.\n\n`;
  md += `---\n\n`;
  md += `**Maintained by:** AFENDA-NEXUS Team\n`;

  return md;
}

function generateInstalled(registry) {
  const now = new Date().toISOString().slice(0, 10);
  const total = registry.skills.length;
  const byCategory = {};
  for (const skill of registry.skills) {
    const cat = skill.category;
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push(skill);
  }

  let md = `<!-- AUTO-GENERATED by .agents/tools/agents-gen.mjs — do not edit manually -->\n`;
  md += `# Installed Skills Reference\n\n`;
  md += `> **Generated:** ${now}  \n`;
  md += `> **Location:** \`.agents/skills\`  \n`;
  md += `> **Total Skills:** ${total}\n\n`;
  md += `---\n\n`;

  let idx = 1;
  for (const [catKey, catLabel] of Object.entries(registry.categories)) {
    const skills = byCategory[catKey];
    if (!skills || skills.length === 0) continue;
    md += `## ${catLabel}\n\n`;
    for (const s of skills) {
      const priority = s.priority === "high" ? "★★★" : s.priority === "medium" ? "★★" : "★";
      md += `### ${idx}. ${s.name} ${priority}\n\n`;
      md += `- **Source:** \`${s.source}\`\n`;
      md += `- **Description:** ${s.description}\n`;
      md += `- **Path:** \`${s.path}\`\n\n`;
      idx++;
    }
  }

  md += `---\n\n`;
  md += `## How to Use\n\n`;
  md += `Skills are automatically available to AI assistants. Reference them by name:\n\n`;
  md += `\`\`\`\n`;
  md += `@next-best-practices   — Next.js patterns and conventions\n`;
  md += `@drizzle               — Database schema and queries\n`;
  md += `@zod                   — Validation and type-safe parsing\n`;
  md += `@shadcn-ui             — UI components\n`;
  md += `@monorepo-management   — Monorepo and workspace setup\n`;
  md += `\`\`\`\n\n`;
  md += `---\n\n`;
  md += `## Updating Skills\n\n`;
  md += `\`\`\`bash\n`;
  md += `npx skills update          # Update all skills\n`;
  md += `npx skills check           # Check for updates\n`;
  md += `node .agents/tools/agents-gen.mjs   # Regenerate docs from registry\n`;
  md += `\`\`\`\n\n`;
  md += `---\n\n`;
  md += `**Maintained by:** AFENDA-NEXUS Team\n`;

  return md;
}

// ─── Main ───────────────────────────────────────────────────────────────────

function main() {
  const registry = loadRegistry();
  const diskSkills = discoverSkillsOnDisk();
  const errors = validate(registry, diskSkills);

  if (errors.length > 0) {
    console.error(`\n[FAIL] Validation errors (${errors.length}):\n`);
    for (const e of errors) console.error(`  - ${e}`);
    console.error("");
    if (CHECK_MODE) process.exit(1);
    console.warn("[WARN] Generating docs despite errors. Fix the above issues.\n");
  } else {
    console.log(`[PASS] Registry validated -- ${registry.skills.length} skills, 0 errors`);
  }

  const indexContent = generateIndex(registry);
  const installedContent = generateInstalled(registry);

  if (CHECK_MODE) {
    const currentIndex = existsSync(INDEX_PATH) ? readFileSync(INDEX_PATH, "utf-8") : "";
    const currentInstalled = existsSync(INSTALLED_PATH) ? readFileSync(INSTALLED_PATH, "utf-8") : "";

    let drifted = false;
    if (currentIndex !== indexContent) {
      console.error("DRIFT: INDEX.md is out of date");
      drifted = true;
    }
    if (currentInstalled !== installedContent) {
      console.error("DRIFT: INSTALLED-SKILLS.md is out of date");
      drifted = true;
    }
    if (drifted) {
      console.error("\nRun `node .agents/tools/agents-gen.mjs` to regenerate.\n");
      process.exit(1);
    }
    console.log("[PASS] Generated docs are up to date");
    return;
  }

  writeFileSync(INDEX_PATH, indexContent, "utf-8");
  console.log(`Generated ${INDEX_PATH}`);

  writeFileSync(INSTALLED_PATH, installedContent, "utf-8");
  console.log(`Generated ${INSTALLED_PATH}`);

  // Update registry timestamp
  registry.generatedAt = new Date().toISOString();
  writeFileSync(REGISTRY_PATH, JSON.stringify(registry, null, 2) + "\n", "utf-8");
  console.log(`Updated registry timestamp`);

  console.log(`\n[PASS] Done -- ${registry.skills.length} skills documented\n`);
}

main();
