import type { IApInvoiceRepo } from './ap-invoice-repo.js';
import type { IPaymentTermsRepo } from './payment-terms-repo.js';
import type { IApPaymentRunRepo } from './payment-run-repo.js';
import type { ISupplierRepo } from './supplier-repo.js';
import type { IApHoldRepo } from './ap-hold-repo.js';
import type { IMatchToleranceRepo } from './match-tolerance-repo.js';
import type { IApPrepaymentRepo } from './prepayment-repo.js';
import type { ISupplierDocumentRepo } from '../services/supplier-portal-document-vault.js';
import type { ISupplierDisputeRepo } from '../services/supplier-portal-dispute.js';
import type { ISupplierNotificationPrefRepo } from '../services/supplier-portal-notifications.js';
import type {
  ISupplierComplianceRepo,
  IComplianceAlertLogRepo,
} from '../services/supplier-portal-compliance.js';
import type { IInvoiceAttachmentRepo } from '../entities/invoice-attachment.js';
import type { IWhtCertificateRepo as IApWhtCertificateRepo } from './wht-certificate-repo.js';
import type { ISupplierBlockRepo } from './supplier-block-repo.js';
import type { ISupplierTaxRepo } from './supplier-tax-repo.js';
import type { ISupplierLegalDocRepo } from './supplier-legal-doc-repo.js';
import type { ISupplierEvalRepo } from './supplier-eval-repo.js';
import type { ISupplierRiskRepo } from './supplier-risk-repo.js';
import type { ISupplierContactRepo } from './supplier-contact-repo.js';
import type { ISupplierDiversityRepo } from './supplier-diversity-repo.js';
import type { ISupplierDuplicateRepo } from './supplier-duplicate-repo.js';
import type { ISupplierCompanyOverrideRepo } from './supplier-company-override-repo.js';
import type { ISupplierAccountGroupRepo } from './supplier-account-group-repo.js';
import type { ISupplierCaseRepo, ICaseTimelineRepo } from '../services/supplier-portal-case.js';
import type { IAuditLogRepo } from '../services/supplier-portal-audit.js';
import type { IOnboardingSubmissionRepo } from '../services/supplier-portal-onboarding.js';
import type { ICompanyLocationRepo } from '../services/supplier-portal-location.js';
import type { IDirectoryRepo } from '../services/supplier-portal-directory.js';
import type { IInvitationRepo } from '../services/supplier-portal-invitation.js';
import type { IMessageThreadRepo, IMessageRepo } from '../services/supplier-portal-messaging.js';
import type { IEscalationRepo } from '../services/supplier-portal-escalation.js';
import type { IAnnouncementRepo } from '../services/supplier-portal-announcement.js';
import type { IMeetingRequestRepo } from '../services/supplier-portal-appointment.js';
import type { IProofChainReader } from '../repos/drizzle-proof-chain-reader.js';
import type { IProofChainWriter } from '@afenda/supplier-kernel';
import type { IPaymentStatusFactRepo } from '../services/supplier-portal-payment-tracking.js';
import type { IEarlyPaymentOfferRepo } from '../services/supplier-portal-scf.js';
import type { IWebhookSubscriptionRepo } from '../services/supplier-portal-webhook.js';
import type { ISupplierAssociationRepo } from '../services/supplier-portal-multi-entity.js';

export interface ApDeps {
  readonly apInvoiceRepo: IApInvoiceRepo;
  readonly paymentTermsRepo: IPaymentTermsRepo;
  readonly apPaymentRunRepo: IApPaymentRunRepo;
  readonly supplierRepo: ISupplierRepo;
  readonly apHoldRepo: IApHoldRepo;
  readonly matchToleranceRepo: IMatchToleranceRepo;
  readonly apPrepaymentRepo: IApPrepaymentRepo;
  readonly invoiceAttachmentRepo: IInvoiceAttachmentRepo;
  readonly supplierDocumentRepo: ISupplierDocumentRepo;
  readonly supplierDisputeRepo: ISupplierDisputeRepo;
  readonly supplierNotificationPrefRepo: ISupplierNotificationPrefRepo;
  readonly supplierComplianceRepo: ISupplierComplianceRepo;
  readonly apWhtCertificateRepo: IApWhtCertificateRepo;
  readonly supplierBlockRepo?: ISupplierBlockRepo;
  readonly supplierTaxRepo?: ISupplierTaxRepo;
  readonly supplierLegalDocRepo?: ISupplierLegalDocRepo;
  readonly supplierEvalRepo?: ISupplierEvalRepo;
  readonly supplierRiskRepo?: ISupplierRiskRepo;
  readonly supplierContactRepo?: ISupplierContactRepo;
  readonly supplierDiversityRepo?: ISupplierDiversityRepo;
  readonly supplierDuplicateRepo?: ISupplierDuplicateRepo;
  readonly supplierCompanyOverrideRepo?: ISupplierCompanyOverrideRepo;
  readonly supplierAccountGroupRepo?: ISupplierAccountGroupRepo;
  readonly supplierCaseRepo?: ISupplierCaseRepo;
  readonly caseTimelineRepo?: ICaseTimelineRepo;
  readonly auditLogRepo?: IAuditLogRepo;
  readonly onboardingSubmissionRepo?: IOnboardingSubmissionRepo;
  readonly onboardingRepo?: IOnboardingSubmissionRepo;
  readonly complianceAlertLogRepo?: IComplianceAlertLogRepo;
  readonly companyLocationRepo?: ICompanyLocationRepo;
  readonly directoryRepo?: IDirectoryRepo;
  readonly invitationRepo?: IInvitationRepo;
  readonly messageThreadRepo?: IMessageThreadRepo;
  readonly messageRepo?: IMessageRepo;
  readonly escalationRepo?: IEscalationRepo;
  readonly announcementRepo?: IAnnouncementRepo;
  readonly meetingRequestRepo?: IMeetingRequestRepo;
  readonly proofChainReader?: IProofChainReader;
  readonly proofChainWriter?: IProofChainWriter;
  readonly paymentStatusFactRepo?: IPaymentStatusFactRepo;
  readonly earlyPaymentOfferRepo?: IEarlyPaymentOfferRepo;
  readonly webhookRepo?: IWebhookSubscriptionRepo;
  readonly supplierAssociationRepo?: ISupplierAssociationRepo;
}
