-- 0001_rls_and_posting_guards.sql
-- Hand-written migration: RLS policies, posting triggers, balance checks
-- These cannot be generated by drizzle-kit — managed manually.
-- Covers AIS items: A-03 (RLS), A-04 (immutable posted journal), A-05 (balanced lines), A-06 (period-open gate)

-- ═══════════════════════════════════════════════════════════════════════════════
-- §1  Context helper functions (required by RLS policies)
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION erp.current_tenant_id()
RETURNS uuid
LANGUAGE sql
STABLE
PARALLEL SAFE
AS $$
  SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid;
$$;

CREATE OR REPLACE FUNCTION erp.current_user_id()
RETURNS uuid
LANGUAGE sql
STABLE
PARALLEL SAFE
AS $$
  SELECT NULLIF(current_setting('app.user_id', true), '')::uuid;
$$;

COMMENT ON FUNCTION erp.current_tenant_id() IS 'Returns tenant_id from SET LOCAL app.tenant_id — used in RLS policies';
COMMENT ON FUNCTION erp.current_user_id() IS 'Returns user_id from SET LOCAL app.user_id — used in posting triggers';

-- ═══════════════════════════════════════════════════════════════════════════════
-- §2  Application runtime role + grants
-- ═══════════════════════════════════════════════════════════════════════════════

DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_runtime') THEN
    CREATE ROLE app_runtime NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_runtime_login') THEN
    CREATE ROLE app_runtime_login LOGIN NOINHERIT;
  END IF;
END
$$;

GRANT app_runtime TO app_runtime_login WITH SET TRUE;
GRANT app_runtime TO neondb_owner WITH SET TRUE;

GRANT USAGE ON SCHEMA platform TO app_runtime;
GRANT USAGE ON SCHEMA erp TO app_runtime;
GRANT USAGE ON SCHEMA audit TO app_runtime;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA platform TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA erp TO app_runtime;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA audit TO app_runtime;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA platform TO app_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA erp TO app_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA audit TO app_runtime;

GRANT EXECUTE ON FUNCTION erp.current_tenant_id() TO app_runtime;
GRANT EXECUTE ON FUNCTION erp.current_user_id() TO app_runtime;

ALTER DEFAULT PRIVILEGES IN SCHEMA platform GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA erp GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT, INSERT ON TABLES TO app_runtime;

ALTER DEFAULT PRIVILEGES IN SCHEMA platform GRANT USAGE, SELECT ON SEQUENCES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA erp GRANT USAGE, SELECT ON SEQUENCES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT USAGE, SELECT ON SEQUENCES TO app_runtime;

-- ═══════════════════════════════════════════════════════════════════════════════
-- §3  A-03: ENABLE ROW LEVEL SECURITY on every tenant table
-- ═══════════════════════════════════════════════════════════════════════════════

-- Platform
ALTER TABLE "platform"."tenant"  ENABLE ROW LEVEL SECURITY;
ALTER TABLE "platform"."company" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "platform"."user"    ENABLE ROW LEVEL SECURITY;

-- ERP (original tables)
ALTER TABLE "erp"."currency"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."fiscal_year"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."fiscal_period"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."account"            ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."ledger"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."gl_journal"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."gl_journal_line"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."gl_balance"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."counterparty"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."ic_agreement"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."ic_transaction"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."ic_transaction_leg" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."outbox"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."fx_rate"            ENABLE ROW LEVEL SECURITY;

-- ERP (P3 tables)
ALTER TABLE "erp"."budget_entry"            ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."classification_rule_set" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."classification_rule"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."ic_settlement"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."ic_settlement_line"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."recurring_template"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."revenue_contract"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."recognition_milestone"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "erp"."idempotency_store"       ENABLE ROW LEVEL SECURITY;

-- Audit
ALTER TABLE "audit"."audit_log" ENABLE ROW LEVEL SECURITY;

-- Force RLS (applies even to table owners)
ALTER TABLE "platform"."tenant"  FORCE ROW LEVEL SECURITY;
ALTER TABLE "platform"."company" FORCE ROW LEVEL SECURITY;
ALTER TABLE "platform"."user"    FORCE ROW LEVEL SECURITY;

ALTER TABLE "erp"."currency"           FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."fiscal_year"        FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."fiscal_period"      FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."account"            FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."ledger"             FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."gl_journal"         FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."gl_journal_line"    FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."gl_balance"         FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."counterparty"       FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."ic_agreement"       FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."ic_transaction"     FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."ic_transaction_leg" FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."outbox"             FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."fx_rate"            FORCE ROW LEVEL SECURITY;

ALTER TABLE "erp"."budget_entry"            FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."classification_rule_set" FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."classification_rule"     FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."ic_settlement"           FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."ic_settlement_line"      FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."recurring_template"      FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."revenue_contract"        FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."recognition_milestone"   FORCE ROW LEVEL SECURITY;
ALTER TABLE "erp"."idempotency_store"       FORCE ROW LEVEL SECURITY;

ALTER TABLE "audit"."audit_log" FORCE ROW LEVEL SECURITY;

-- ─── Tenant Isolation Policies ────────────────────────────────────────────────
-- DROP IF EXISTS for idempotency (safe to re-run)

-- platform.tenant — tenant can only see its own row
DROP POLICY IF EXISTS "tenant_isolation" ON "platform"."tenant";
CREATE POLICY "tenant_isolation" ON "platform"."tenant"
  FOR ALL TO app_runtime
  USING ("id" = erp.current_tenant_id())
  WITH CHECK ("id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "platform"."company";
CREATE POLICY "tenant_isolation" ON "platform"."company"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "platform"."user";
CREATE POLICY "tenant_isolation" ON "platform"."user"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."currency";
CREATE POLICY "tenant_isolation" ON "erp"."currency"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."fiscal_year";
CREATE POLICY "tenant_isolation" ON "erp"."fiscal_year"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."fiscal_period";
CREATE POLICY "tenant_isolation" ON "erp"."fiscal_period"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."account";
CREATE POLICY "tenant_isolation" ON "erp"."account"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."ledger";
CREATE POLICY "tenant_isolation" ON "erp"."ledger"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."gl_journal";
CREATE POLICY "tenant_isolation" ON "erp"."gl_journal"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."gl_journal_line";
CREATE POLICY "tenant_isolation" ON "erp"."gl_journal_line"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."gl_balance";
CREATE POLICY "tenant_isolation" ON "erp"."gl_balance"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."counterparty";
CREATE POLICY "tenant_isolation" ON "erp"."counterparty"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."ic_agreement";
CREATE POLICY "tenant_isolation" ON "erp"."ic_agreement"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."ic_transaction";
CREATE POLICY "tenant_isolation" ON "erp"."ic_transaction"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."ic_transaction_leg";
CREATE POLICY "tenant_isolation" ON "erp"."ic_transaction_leg"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."outbox";
CREATE POLICY "tenant_isolation" ON "erp"."outbox"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."fx_rate";
CREATE POLICY "tenant_isolation" ON "erp"."fx_rate"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."budget_entry";
CREATE POLICY "tenant_isolation" ON "erp"."budget_entry"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."classification_rule_set";
CREATE POLICY "tenant_isolation" ON "erp"."classification_rule_set"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."classification_rule";
CREATE POLICY "tenant_isolation" ON "erp"."classification_rule"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."ic_settlement";
CREATE POLICY "tenant_isolation" ON "erp"."ic_settlement"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."ic_settlement_line";
CREATE POLICY "tenant_isolation" ON "erp"."ic_settlement_line"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."recurring_template";
CREATE POLICY "tenant_isolation" ON "erp"."recurring_template"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."revenue_contract";
CREATE POLICY "tenant_isolation" ON "erp"."revenue_contract"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."recognition_milestone";
CREATE POLICY "tenant_isolation" ON "erp"."recognition_milestone"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "erp"."idempotency_store";
CREATE POLICY "tenant_isolation" ON "erp"."idempotency_store"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

DROP POLICY IF EXISTS "tenant_isolation" ON "audit"."audit_log";
CREATE POLICY "tenant_isolation" ON "audit"."audit_log"
  FOR ALL TO app_runtime
  USING ("tenant_id" = erp.current_tenant_id())
  WITH CHECK ("tenant_id" = erp.current_tenant_id());

-- ═══════════════════════════════════════════════════════════════════════════════
-- §4  A-04: Immutable posted journal (BEFORE trigger)
--     A-06: Period-open gate (also enforced in BEFORE trigger)
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION erp.trg_journal_before_post()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_period_status text;
BEGIN
  -- A-04: Immutability — prevent updates on POSTED/REVERSED/VOIDED journals
  IF TG_OP = 'UPDATE' AND OLD.status IN ('POSTED', 'REVERSED', 'VOIDED') THEN
    -- Allow only status transitions: POSTED→REVERSED, POSTED→VOIDED
    IF NEW.status = OLD.status THEN
      RAISE EXCEPTION 'Cannot modify a % journal', OLD.status;
    END IF;
    IF OLD.status = 'POSTED' AND NEW.status NOT IN ('REVERSED', 'VOIDED') THEN
      RAISE EXCEPTION 'POSTED journal can only transition to REVERSED or VOIDED, not %', NEW.status;
    END IF;
    IF OLD.status IN ('REVERSED', 'VOIDED') THEN
      RAISE EXCEPTION 'Cannot change status of a % journal', OLD.status;
    END IF;
  END IF;

  -- Set posting metadata when transitioning to POSTED
  IF NEW.status = 'POSTED' AND (OLD IS NULL OR OLD.status <> 'POSTED') THEN
    NEW.posted_at := now();
    NEW.posted_by := erp.current_user_id();

    -- A-06: Period-open gate — DB-level backstop
    SELECT fp.status INTO v_period_status
    FROM erp.fiscal_period fp
    WHERE fp.id = NEW.fiscal_period_id AND fp.tenant_id = NEW.tenant_id;

    IF v_period_status IS NULL THEN
      RAISE EXCEPTION 'Fiscal period % not found for tenant %', NEW.fiscal_period_id, NEW.tenant_id;
    END IF;
    IF v_period_status <> 'OPEN' THEN
      RAISE EXCEPTION 'Cannot post journal to % period (must be OPEN)', v_period_status;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_journal_before_post ON "erp"."gl_journal";
CREATE TRIGGER trg_journal_before_post
  BEFORE INSERT OR UPDATE ON "erp"."gl_journal"
  FOR EACH ROW
  EXECUTE FUNCTION erp.trg_journal_before_post();

-- ═══════════════════════════════════════════════════════════════════════════════
-- §5  A-05: Balanced journal lines (DEFERRABLE AFTER trigger)
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION erp.trg_journal_after_post()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_debit_sum bigint;
  v_credit_sum bigint;
BEGIN
  -- Only validate when journal is being posted
  IF NEW.status <> 'POSTED' THEN
    RETURN NEW;
  END IF;

  SELECT COALESCE(SUM(debit), 0), COALESCE(SUM(credit), 0)
  INTO v_debit_sum, v_credit_sum
  FROM "erp"."gl_journal_line"
  WHERE journal_id = NEW.id AND tenant_id = NEW.tenant_id;

  IF v_debit_sum <> v_credit_sum THEN
    RAISE EXCEPTION 'Journal % is unbalanced: debits=% credits=%',
      NEW.journal_number, v_debit_sum, v_credit_sum;
  END IF;

  IF v_debit_sum = 0 THEN
    RAISE EXCEPTION 'Journal % has no lines', NEW.journal_number;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_journal_after_post ON "erp"."gl_journal";
CREATE CONSTRAINT TRIGGER trg_journal_after_post
  AFTER INSERT OR UPDATE ON "erp"."gl_journal"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  EXECUTE FUNCTION erp.trg_journal_after_post();

-- ═══════════════════════════════════════════════════════════════════════════════
-- §6  Journal line immutability (prevent changes after posting)
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION erp.trg_journal_line_immutable()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_status text;
BEGIN
  SELECT status INTO v_status
  FROM "erp"."gl_journal"
  WHERE id = COALESCE(OLD.journal_id, NEW.journal_id)
    AND tenant_id = COALESCE(OLD.tenant_id, NEW.tenant_id);

  IF v_status IN ('POSTED', 'REVERSED', 'VOIDED') THEN
    RAISE EXCEPTION 'Cannot modify lines of a % journal', v_status;
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_journal_line_immutable ON "erp"."gl_journal_line";
CREATE TRIGGER trg_journal_line_immutable
  BEFORE INSERT OR UPDATE OR DELETE ON "erp"."gl_journal_line"
  FOR EACH ROW
  EXECUTE FUNCTION erp.trg_journal_line_immutable();

-- ═══════════════════════════════════════════════════════════════════════════════
-- §7  Grant execute on trigger functions
-- ═══════════════════════════════════════════════════════════════════════════════

GRANT EXECUTE ON FUNCTION erp.trg_journal_before_post() TO app_runtime;
GRANT EXECUTE ON FUNCTION erp.trg_journal_after_post() TO app_runtime;
GRANT EXECUTE ON FUNCTION erp.trg_journal_line_immutable() TO app_runtime;
