CREATE INDEX "idx_audit_log_table_record" ON "audit"."audit_log" USING btree ("tenant_id","table_name","record_id");--> statement-breakpoint
CREATE INDEX "idx_audit_log_user" ON "audit"."audit_log" USING btree ("tenant_id","user_id");--> statement-breakpoint
CREATE INDEX "idx_audit_log_occurred" ON "audit"."audit_log" USING btree ("tenant_id","occurred_at");--> statement-breakpoint
CREATE INDEX "idx_approval_policy_entity_type" ON "erp"."approval_policy" USING btree ("tenant_id","entity_type","is_active");--> statement-breakpoint
CREATE INDEX "idx_approval_policy_company" ON "erp"."approval_policy" USING btree ("tenant_id","company_id");--> statement-breakpoint
CREATE INDEX "idx_approval_request_entity" ON "erp"."approval_request" USING btree ("tenant_id","entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "idx_approval_request_status" ON "erp"."approval_request" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE INDEX "idx_approval_request_requester" ON "erp"."approval_request" USING btree ("tenant_id","requested_by");--> statement-breakpoint
CREATE INDEX "idx_approval_step_request" ON "erp"."approval_step" USING btree ("tenant_id","request_id");--> statement-breakpoint
CREATE INDEX "idx_approval_step_approver_status" ON "erp"."approval_step" USING btree ("tenant_id","approver_id","status");--> statement-breakpoint
CREATE INDEX "idx_sod_action_entity" ON "erp"."sod_action_log" USING btree ("tenant_id","entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "idx_sod_action_actor" ON "erp"."sod_action_log" USING btree ("tenant_id","actor_id");--> statement-breakpoint
CREATE INDEX "idx_accounting_event_date" ON "erp"."accounting_event" USING btree ("tenant_id","event_date");--> statement-breakpoint
CREATE INDEX "idx_account_parent" ON "erp"."account" USING btree ("tenant_id","parent_id");--> statement-breakpoint
CREATE INDEX "idx_ap_invoice_date" ON "erp"."ap_invoice" USING btree ("tenant_id","invoice_date");--> statement-breakpoint
CREATE INDEX "idx_ap_invoice_company_status" ON "erp"."ap_invoice" USING btree ("tenant_id","company_id","status");--> statement-breakpoint
CREATE INDEX "idx_ap_run_item_supplier" ON "erp"."ap_payment_run_item" USING btree ("tenant_id","supplier_id");--> statement-breakpoint
CREATE INDEX "idx_ap_payment_run_date" ON "erp"."ap_payment_run" USING btree ("tenant_id","run_date");--> statement-breakpoint
CREATE INDEX "idx_ar_alloc_item_invoice" ON "erp"."ar_allocation_item" USING btree ("tenant_id","invoice_id");--> statement-breakpoint
CREATE INDEX "idx_ar_invoice_line_account" ON "erp"."ar_invoice_line" USING btree ("tenant_id","account_id");--> statement-breakpoint
CREATE INDEX "idx_ar_invoice_company" ON "erp"."ar_invoice" USING btree ("tenant_id","company_id");--> statement-breakpoint
CREATE INDEX "idx_ar_invoice_date" ON "erp"."ar_invoice" USING btree ("tenant_id","invoice_date");--> statement-breakpoint
CREATE INDEX "idx_ar_payment_alloc_date" ON "erp"."ar_payment_allocation" USING btree ("tenant_id","payment_date");--> statement-breakpoint
CREATE INDEX "idx_asset_category" ON "erp"."asset" USING btree ("tenant_id","category_code");--> statement-breakpoint
CREATE INDEX "idx_bank_line_date" ON "erp"."bank_statement_line" USING btree ("tenant_id","transaction_date");--> statement-breakpoint
CREATE INDEX "idx_bank_stmt_date" ON "erp"."bank_statement" USING btree ("tenant_id","statement_date");--> statement-breakpoint
CREATE INDEX "idx_cost_center_status" ON "erp"."cost_center" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE INDEX "idx_counterparty_type" ON "erp"."counterparty" USING btree ("tenant_id","counterparty_type");--> statement-breakpoint
CREATE INDEX "idx_depr_schedule_period" ON "erp"."depreciation_schedule" USING btree ("tenant_id","period_start","period_end");--> statement-breakpoint
CREATE INDEX "idx_expense_claim_company" ON "erp"."expense_claim" USING btree ("tenant_id","company_id");--> statement-breakpoint
CREATE INDEX "idx_fiscal_period_status" ON "erp"."fiscal_period" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE INDEX "idx_lease_schedule_payment" ON "erp"."lease_schedule" USING btree ("tenant_id","payment_date");--> statement-breakpoint
CREATE INDEX "idx_project_manager" ON "erp"."project" USING btree ("tenant_id","manager_id");--> statement-breakpoint
CREATE INDEX "idx_tax_code_parent" ON "erp"."tax_code" USING btree ("tenant_id","parent_id");--> statement-breakpoint
CREATE INDEX "idx_tax_rate_effective" ON "erp"."tax_rate" USING btree ("tenant_id","effective_from");--> statement-breakpoint
CREATE INDEX "idx_admin_action_user" ON "platform"."admin_action_log" USING btree ("admin_user_id","occurred_at");--> statement-breakpoint
CREATE INDEX "idx_admin_action_tenant" ON "platform"."admin_action_log" USING btree ("target_tenant_id","occurred_at");