/** @generated by afenda-gen — DO NOT EDIT BY HAND */

export type GeneratedEmptyStateKey =
  // @afenda-gen:empty-state-keys:start
  | 'finance.payables.duplicates'
  | 'finance.payables.creditMemos'
  | 'finance.payables.debitMemos'
  | 'finance.payables.prepayments'
  | 'finance.payables.triage'
  | 'finance.payables.reconciliation'
  | 'finance.payables.import'
  | 'finance.payables.closeChecklist';
  // @afenda-gen:empty-state-keys:end
