/**
 * W2-8: Stable AP error code enum.
 *
 * Every AP service error MUST use one of these codes.
 * The error mapper translates these to deterministic HTTP statuses.
 * New codes must be added here AND in the error-mapper switch.
 */
export const ApErrorCode = {
  // 400 — Bad Request
  INVALID_INVOICE_INPUT: 'AP_INVALID_INVOICE_INPUT',
  INVALID_HOLD_INPUT: 'AP_INVALID_HOLD_INPUT',
  INVALID_SUPPLIER_INPUT: 'AP_INVALID_SUPPLIER_INPUT',

  // 404 — Not Found
  INVOICE_NOT_FOUND: 'AP_INVOICE_NOT_FOUND',
  SUPPLIER_NOT_FOUND: 'AP_SUPPLIER_NOT_FOUND',
  HOLD_NOT_FOUND: 'AP_HOLD_NOT_FOUND',
  PAYMENT_RUN_NOT_FOUND: 'AP_PAYMENT_RUN_NOT_FOUND',
  PAYMENT_TERMS_NOT_FOUND: 'AP_PAYMENT_TERMS_NOT_FOUND',

  // 409 — Conflict (state violations)
  INVOICE_ALREADY_POSTED: 'AP_INVOICE_ALREADY_POSTED',
  INVOICE_ALREADY_PAID: 'AP_INVOICE_ALREADY_PAID',
  INVOICE_CANCELLED: 'AP_INVOICE_CANCELLED',
  HOLD_ALREADY_RELEASED: 'AP_HOLD_ALREADY_RELEASED',
  PAYMENT_RUN_NOT_APPROVED: 'AP_PAYMENT_RUN_NOT_APPROVED',
  PAYMENT_RUN_ALREADY_EXECUTED: 'AP_PAYMENT_RUN_ALREADY_EXECUTED',
  PAYMENT_RUN_NOT_EXECUTED: 'AP_PAYMENT_RUN_NOT_EXECUTED',

  // 422 — Unprocessable (domain rule violations)
  INVOICE_HAS_ACTIVE_HOLDS: 'AP_INVOICE_HAS_ACTIVE_HOLDS',
  INVOICE_HAS_PARTIAL_PAYMENT: 'AP_INVOICE_HAS_PARTIAL_PAYMENT',
  DUPLICATE_DETECTED: 'AP_DUPLICATE_DETECTED',
  MATCH_OVER_TOLERANCE: 'AP_MATCH_OVER_TOLERANCE',
  PERIOD_CLOSED: 'AP_PERIOD_CLOSED',
  PAYMENT_RUN_EMPTY: 'AP_PAYMENT_RUN_EMPTY',

  // 403 — Supplier portal scope violations
  SUPPLIER_SCOPE_MISMATCH: 'AP_SUPPLIER_SCOPE_MISMATCH',

  // 422 — Supplier portal domain rule violations
  SUPPLIER_BANK_ACCOUNT_VALIDATION: 'AP_SUPPLIER_BANK_ACCOUNT_VALIDATION',
  SUPPLIER_INVOICE_SUBMISSION_INVALID: 'AP_SUPPLIER_INVOICE_SUBMISSION_INVALID',
  SUPPLIER_PROFILE_FIELD_RESTRICTED: 'AP_SUPPLIER_PROFILE_FIELD_RESTRICTED',
  SUPPLIER_STATEMENT_EMPTY: 'AP_SUPPLIER_STATEMENT_EMPTY',
  SUPPLIER_DOCUMENT_TYPE_INVALID: 'AP_SUPPLIER_DOCUMENT_TYPE_INVALID',
  SUPPLIER_DISPUTE_INVALID: 'AP_SUPPLIER_DISPUTE_INVALID',

  // 404 — Supplier portal not found
  SUPPLIER_DISPUTE_NOT_FOUND: 'AP_SUPPLIER_DISPUTE_NOT_FOUND',
  SUPPLIER_DOCUMENT_NOT_FOUND: 'AP_SUPPLIER_DOCUMENT_NOT_FOUND',

  // 409 — Supplier portal conflict
  SUPPLIER_DISPUTE_ALREADY_RESOLVED: 'AP_SUPPLIER_DISPUTE_ALREADY_RESOLVED',
} as const;

export type ApErrorCode = (typeof ApErrorCode)[keyof typeof ApErrorCode];
