'use server';

import type {
  CostCenter,
  CostDriver,
  CostDriverValue,
  AllocationRule,
  AllocationRun,
  AllocationDetail,
  CostAccountingSummary,
} from '../types';

// ─── Mock Data ───────────────────────────────────────────────────────────────

const mockCostCenters: CostCenter[] = [
  {
    id: 'cc-1',
    code: 'CORP',
    name: 'Corporate',
    description: 'Corporate headquarters',
    type: 'department',
    parentId: null,
    parentCode: null,
    managerId: 'mgr-1',
    managerName: 'John Smith',
    budgetAmount: 5000000,
    actualAmount: 4250000,
    currency: 'USD',
    status: 'active',
    level: 0,
    path: ['CORP'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'cc-2',
    code: 'FIN',
    name: 'Finance',
    description: 'Finance department',
    type: 'department',
    parentId: 'cc-1',
    parentCode: 'CORP',
    managerId: 'mgr-2',
    managerName: 'Jane Doe',
    budgetAmount: 1200000,
    actualAmount: 1100000,
    currency: 'USD',
    status: 'active',
    level: 1,
    path: ['CORP', 'FIN'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'cc-3',
    code: 'HR',
    name: 'Human Resources',
    description: 'HR department',
    type: 'department',
    parentId: 'cc-1',
    parentCode: 'CORP',
    managerId: 'mgr-3',
    managerName: 'Mike Johnson',
    budgetAmount: 800000,
    actualAmount: 750000,
    currency: 'USD',
    status: 'active',
    level: 1,
    path: ['CORP', 'HR'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'cc-4',
    code: 'IT',
    name: 'Information Technology',
    description: 'IT department',
    type: 'department',
    parentId: 'cc-1',
    parentCode: 'CORP',
    managerId: 'mgr-4',
    managerName: 'Sarah Wilson',
    budgetAmount: 1500000,
    actualAmount: 1450000,
    currency: 'USD',
    status: 'active',
    level: 1,
    path: ['CORP', 'IT'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2026-02-18'),
  },
  {
    id: 'cc-5',
    code: 'SALES',
    name: 'Sales',
    description: 'Sales department',
    type: 'department',
    parentId: null,
    parentCode: null,
    managerId: 'mgr-5',
    managerName: 'Tom Brown',
    budgetAmount: 3000000,
    actualAmount: 2850000,
    currency: 'USD',
    status: 'active',
    level: 0,
    path: ['SALES'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2026-02-22'),
  },
  {
    id: 'cc-6',
    code: 'MFG',
    name: 'Manufacturing',
    description: 'Manufacturing operations',
    type: 'location',
    parentId: null,
    parentCode: null,
    managerId: 'mgr-6',
    managerName: 'Lisa Chen',
    budgetAmount: 8000000,
    actualAmount: 7800000,
    currency: 'USD',
    status: 'active',
    level: 0,
    path: ['MFG'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2026-02-25'),
  },
];

const mockDrivers: CostDriver[] = [
  {
    id: 'drv-1',
    code: 'HC',
    name: 'Headcount',
    description: 'Number of full-time employees',
    type: 'headcount',
    unit: 'FTE',
    status: 'active',
    effectiveFrom: new Date('2024-01-01'),
    effectiveTo: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'drv-2',
    code: 'REV',
    name: 'Revenue',
    description: 'Revenue generated by cost center',
    type: 'revenue',
    unit: 'USD',
    status: 'active',
    effectiveFrom: new Date('2024-01-01'),
    effectiveTo: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'drv-3',
    code: 'SQFT',
    name: 'Square Footage',
    description: 'Occupied floor space',
    type: 'square_footage',
    unit: 'sq ft',
    status: 'active',
    effectiveFrom: new Date('2024-01-01'),
    effectiveTo: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'drv-4',
    code: 'MH',
    name: 'Machine Hours',
    description: 'Production machine hours used',
    type: 'machine_hours',
    unit: 'hours',
    status: 'active',
    effectiveFrom: new Date('2024-01-01'),
    effectiveTo: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

const mockDriverValues: CostDriverValue[] = [
  {
    id: 'dv-1',
    driverId: 'drv-1',
    costCenterId: 'cc-2',
    costCenterCode: 'FIN',
    costCenterName: 'Finance',
    period: '2026-02',
    value: 25,
    percentage: 15,
    updatedAt: new Date(),
  },
  {
    id: 'dv-2',
    driverId: 'drv-1',
    costCenterId: 'cc-3',
    costCenterCode: 'HR',
    costCenterName: 'Human Resources',
    period: '2026-02',
    value: 12,
    percentage: 7,
    updatedAt: new Date(),
  },
  {
    id: 'dv-3',
    driverId: 'drv-1',
    costCenterId: 'cc-4',
    costCenterCode: 'IT',
    costCenterName: 'Information Technology',
    period: '2026-02',
    value: 45,
    percentage: 27,
    updatedAt: new Date(),
  },
  {
    id: 'dv-4',
    driverId: 'drv-1',
    costCenterId: 'cc-5',
    costCenterCode: 'SALES',
    costCenterName: 'Sales',
    period: '2026-02',
    value: 60,
    percentage: 36,
    updatedAt: new Date(),
  },
  {
    id: 'dv-5',
    driverId: 'drv-1',
    costCenterId: 'cc-6',
    costCenterCode: 'MFG',
    costCenterName: 'Manufacturing',
    period: '2026-02',
    value: 25,
    percentage: 15,
    updatedAt: new Date(),
  },
];

const mockRules: AllocationRule[] = [
  {
    id: 'rule-1',
    name: 'IT Allocation by Headcount',
    description: 'Allocate IT costs to departments based on headcount',
    sourceCostCenterId: 'cc-4',
    sourceCostCenterCode: 'IT',
    sourceCostCenterName: 'Information Technology',
    driverId: 'drv-1',
    driverCode: 'HC',
    driverName: 'Headcount',
    method: 'direct',
    isActive: true,
    order: 1,
    targets: [
      { costCenterId: 'cc-2', costCenterCode: 'FIN', costCenterName: 'Finance', percentage: 26 },
      {
        costCenterId: 'cc-3',
        costCenterCode: 'HR',
        costCenterName: 'Human Resources',
        percentage: 12,
      },
      { costCenterId: 'cc-5', costCenterCode: 'SALES', costCenterName: 'Sales', percentage: 62 },
    ],
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'rule-2',
    name: 'HR Allocation by Headcount',
    description: 'Allocate HR costs to all departments',
    sourceCostCenterId: 'cc-3',
    sourceCostCenterCode: 'HR',
    sourceCostCenterName: 'Human Resources',
    driverId: 'drv-1',
    driverCode: 'HC',
    driverName: 'Headcount',
    method: 'step_down',
    isActive: true,
    order: 2,
    targets: [
      { costCenterId: 'cc-2', costCenterCode: 'FIN', costCenterName: 'Finance', percentage: 19 },
      {
        costCenterId: 'cc-4',
        costCenterCode: 'IT',
        costCenterName: 'Information Technology',
        percentage: 35,
      },
      { costCenterId: 'cc-5', costCenterCode: 'SALES', costCenterName: 'Sales', percentage: 46 },
    ],
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2026-01-15'),
  },
];

const mockRuns: AllocationRun[] = [
  {
    id: 'run-1',
    runNumber: 'ALLOC-2026-001',
    period: '2026-01',
    method: 'step_down',
    status: 'completed',
    totalAllocated: 485000,
    currency: 'USD',
    rulesApplied: 2,
    costCentersAffected: 5,
    journalEntryId: 'je-alloc-1',
    journalEntryNumber: 'JE-2026-0089',
    initiatedBy: 'admin@company.com',
    initiatedAt: new Date('2026-01-31'),
    completedAt: new Date('2026-01-31'),
    reversedAt: null,
    reversedBy: null,
  },
  {
    id: 'run-2',
    runNumber: 'ALLOC-2026-002',
    period: '2026-02',
    method: 'step_down',
    status: 'draft',
    totalAllocated: 0,
    currency: 'USD',
    rulesApplied: 0,
    costCentersAffected: 0,
    journalEntryId: null,
    journalEntryNumber: null,
    initiatedBy: 'admin@company.com',
    initiatedAt: new Date('2026-02-25'),
    completedAt: null,
    reversedAt: null,
    reversedBy: null,
  },
];

// ─── Query Functions ─────────────────────────────────────────────────────────

export async function getCostCenters(params?: {
  status?: string;
  type?: string;
  parentId?: string | null;
  search?: string;
}): Promise<{ ok: true; data: CostCenter[] } | { ok: false; error: string }> {
  await new Promise((r) => setTimeout(r, 300));

  let filtered = [...mockCostCenters];

  if (params?.status) {
    filtered = filtered.filter((cc) => cc.status === params.status);
  }

  if (params?.type) {
    filtered = filtered.filter((cc) => cc.type === params.type);
  }

  if (params?.parentId !== undefined) {
    filtered = filtered.filter((cc) => cc.parentId === params.parentId);
  }

  if (params?.search) {
    const search = params.search.toLowerCase();
    filtered = filtered.filter(
      (cc) => cc.code.toLowerCase().includes(search) || cc.name.toLowerCase().includes(search)
    );
  }

  return { ok: true, data: filtered };
}

export async function getCostCenterTree(): Promise<
  { ok: true; data: CostCenter[] } | { ok: false; error: string }
> {
  await new Promise((r) => setTimeout(r, 400));

  const buildTree = (items: CostCenter[], parentId: string | null): CostCenter[] => {
    return items
      .filter((item) => item.parentId === parentId)
      .map((item) => ({
        ...item,
        children: buildTree(items, item.id),
      }));
  };

  const tree = buildTree(mockCostCenters, null);
  return { ok: true, data: tree };
}

export async function getCostCenterById(
  id: string
): Promise<{ ok: true; data: CostCenter } | { ok: false; error: string }> {
  await new Promise((r) => setTimeout(r, 200));
  const cc = mockCostCenters.find((c) => c.id === id);
  if (!cc) return { ok: false, error: 'Cost center not found' };
  return { ok: true, data: cc };
}

export async function getCostDrivers(): Promise<
  { ok: true; data: CostDriver[] } | { ok: false; error: string }
> {
  await new Promise((r) => setTimeout(r, 250));
  return { ok: true, data: mockDrivers };
}

export async function getCostDriverValues(
  driverId: string,
  period: string
): Promise<{ ok: true; data: CostDriverValue[] } | { ok: false; error: string }> {
  await new Promise((r) => setTimeout(r, 300));
  const values = mockDriverValues.filter((v) => v.driverId === driverId && v.period === period);
  return { ok: true, data: values };
}

export async function getAllocationRules(): Promise<
  { ok: true; data: AllocationRule[] } | { ok: false; error: string }
> {
  await new Promise((r) => setTimeout(r, 300));
  return { ok: true, data: mockRules };
}

export async function getAllocationRuns(params?: {
  status?: string;
  period?: string;
}): Promise<{ ok: true; data: AllocationRun[] } | { ok: false; error: string }> {
  await new Promise((r) => setTimeout(r, 300));

  let filtered = [...mockRuns];

  if (params?.status) {
    filtered = filtered.filter((r) => r.status === params.status);
  }

  if (params?.period) {
    filtered = filtered.filter((r) => r.period === params.period);
  }

  return { ok: true, data: filtered };
}

export async function getAllocationRunById(
  id: string
): Promise<
  { ok: true; data: AllocationRun; details: AllocationDetail[] } | { ok: false; error: string }
> {
  await new Promise((r) => setTimeout(r, 350));
  const run = mockRuns.find((r) => r.id === id);
  if (!run) return { ok: false, error: 'Allocation run not found' };

  const details: AllocationDetail[] = [
    {
      id: 'det-1',
      runId: id,
      ruleId: 'rule-1',
      ruleName: 'IT Allocation by Headcount',
      fromCostCenterId: 'cc-4',
      fromCostCenterCode: 'IT',
      fromCostCenterName: 'Information Technology',
      toCostCenterId: 'cc-2',
      toCostCenterCode: 'FIN',
      toCostCenterName: 'Finance',
      amount: 97500,
      percentage: 26,
      driverValue: 25,
    },
    {
      id: 'det-2',
      runId: id,
      ruleId: 'rule-1',
      ruleName: 'IT Allocation by Headcount',
      fromCostCenterId: 'cc-4',
      fromCostCenterCode: 'IT',
      fromCostCenterName: 'Information Technology',
      toCostCenterId: 'cc-5',
      toCostCenterCode: 'SALES',
      toCostCenterName: 'Sales',
      amount: 232500,
      percentage: 62,
      driverValue: 60,
    },
  ];

  return { ok: true, data: run, details };
}

export async function getCostAccountingSummary(): Promise<
  { ok: true; data: CostAccountingSummary } | { ok: false; error: string }
> {
  await new Promise((r) => setTimeout(r, 250));

  const summary: CostAccountingSummary = {
    totalCostCenters: 12,
    activeCostCenters: 10,
    totalDrivers: 4,
    totalRules: 8,
    lastAllocationRun: '2026-01',
    totalAllocatedYTD: 485000,
    budgetVariancePercent: -5.2,
    pendingAllocations: 1,
  };

  return { ok: true, data: summary };
}
